export const PRODUCT = "PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCRESE_QUANTITY = "INCRESE_QUANTITY";
export const DECRESE_QUANTITY = "DECRESE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";