export const PRODUCT = "PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCRESE_QUANTITY = "INCRESE_QUANTITY";
export const DECRESE_QUANTITY = "DECRESE_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_PRODUCT_BY_SEARCH_TEXT = "FETCH_PRODUCT_BY_SEARCH_TEXT";
export const FETCH_PRODUCT_BY_CATEGORY = "FETCH_PRODUCT_BY_CATEGORY";